package edu.oswego.cs.ytsync;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;
import edu.oswego.cs.ytsync.client.ClientApp;
import edu.oswego.cs.ytsync.server.Server;
import javafx.application.Application;

import java.io.IOException;

public class App {
	@Parameter (names = "-server")
    private boolean isServer = false;

	public static void main(String[] args) throws IOException {
        App app = new App();
        JCommander.newBuilder()
                .addObject(app)
                .build()
                .parse(args);

        app.run(args);
	}

	private void run(String[] args) throws IOException {
	    if(isServer) {
            Server.main(args);
        } else {
            Application.launch(ClientApp.class, args);
        }
    }
}
