package edu.oswego.cs.ytsync;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import edu.oswego.cs.ytsync.client.ClientApp;
import edu.oswego.cs.ytsync.server.Server;
import javafx.application.Application;

import java.io.IOException;
import java.util.Arrays;

public class App {

	public static void main(String[] args) throws IOException {
        if(Arrays.asList(args).contains("-server")) {
            Server.main(args);
        } else {
            Application.launch(ClientApp.class, args);
        }
	}
}
