package edu.oswego.cs.ytsync;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import edu.oswego.cs.ytsync.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

}
