/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	private static final String timeServer = "time-a.nist.gov";

	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());

		SyncedTime commonTime = new SyncedTime(timeServer);
		System.out.println("Common time is: " + commonTime.getTime());
		System.out.println("Time difference between the system and common time is: "
				+ (commonTime.getTime() - System.currentTimeMillis()));
	}
}
